apiVersion: v1
kind: Secret
metadata:
  name: "sharedVolume-{{ template "fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    job-name: {{ template "fullname" . }}
type: Opaque
data:
{{ if and .Values.agent.sharedVolume.accountname .Values.agent.sharedVolume.accountkey }}
  azurestorageaccountname: {{ .Values.agent.sharedVolume.accountname }}
  azurestorageaccountkey: {{ .Values.agent.sharedVolume.accountkey }}
{{ end }}
