apiVersion: v1
kind: Secret
metadata:
  name: "token-{{ template "fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    job-name: {{ template "fullname" . }}
type: Opaque
data:
  pipelinesToken: {{ .Values.devops.token }}
